spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easyrh?useTimezone=true&serverTimezone=UTC
    username: root
    password: adm123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false # Apenas usar quando estiver debugando

# Definindo valor da secrete key
api:
  security:
    secret: ${env:JWT_SECRET:testedesecretkeymalucapaenasparateste}
    expire-lenght: 2

springdoc:
    pathsToMatch: "/api/**/v1/**" 
    swagger-ui:
      use-root-path: true


